## Ch·ªçn c·ªôt

### Khai b√°o th∆∞ vi·ªán

In [1]:
import pandas as pd

### ƒê·ªçc file LiverpoolFC.csv

In [2]:
df = pd.read_csv('C:/Users/Admin/aim/project_analysis_data_facebook/data/LiverpoolFC.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   post_id                        100 non-null    float64
 1   text                           98 non-null     object
 2   post_text                      98 non-null     object
 3   shared_text                    21 non-null     object
 4   original_text                  76 non-null     object
 5   time                           100 non-null    object
 6   timestamp                      100 non-null    int64
 7   image                          37 non-null     object
 8   image_lowquality               100 non-null    object
 9   images                         100 non-null    object
 10  images_description             100 non-null    object
 11  images_lowquality              100 non-null    object
 12  images_lowquality_description  100 non-null    object
 13  video                          41 non-null     object
 14  video_duration_seconds         0 non-null      float64
 15  video_height                   0 non-null      float64
 16  video_id                       41 non-null     float64
 17  video_quality                  0 non-null      float64
 18  video_size_MB                  0 non-null      float64
 19  video_thumbnail                41 non-null     object
 20  video_watches                  0 non-null      float64
 21  video_width                    0 non-null      float64
 22  likes                          0 non-null      float64
 23  comments                       100 non-null    int64
 24  shares                         100 non-null    int64
 25  post_url                       100 non-null    object
 26  link                           23 non-null     object
 27  links                          98 non-null     object
 28  user_id                        100 non-null    float64
 29  username                       100 non-null    object
 30  user_url                       100 non-null    object
 31  is_live                        100 non-null    bool
 32  factcheck                      0 non-null      float64
 33  shared_post_id                 0 non-null      float64
 34  shared_time                    0 non-null      float64
 35  shared_user_id                 0 non-null      float64
 36  shared_username                0 non-null      float64
 37  shared_post_url                0 non-null      float64
 38  available                      100 non-null    bool
 39  comments_full                  100 non-null    object
 40  reactors                       98 non-null     object
 41  w3_fb_url                      99 non-null     object
 42  reactions                      100 non-null    object
 43  reaction_count                 100 non-null    int64
 44  with                           2 non-null      object
 45  page_id                        100 non-null    int64
 46  sharers                        0 non-null      float64
 47  image_id                       23 non-null     float64
 48  image_ids                      100 non-null    object
 49  was_live                       100 non-null    bool
 50  fetched_time                   99 non-null     object
dtypes: bool(3), float64(18), int64(5), object(25)
memory usage: 37.9+ KB

In [4]:
df

,post_id,text,post_text,shared_text,original_text,time,timestamp,image,image_lowquality,images,...,w3_fb_url,reactions,reaction_count,with,page_id,sharers,image_id,image_ids,was_live,fetched_time
0,8.992690e+14,üî¥üó£Ô∏è Emile Heskey is the latest to tell the tal...,üî¥üó£Ô∏è Emile Heskey is the latest to tell the tal...,LIVERPOOLFC.COM\nMy Liverpool Story‚Ä¶ with Emil...,üî¥üó£Ô∏è Emile Heskey is the latest to tell the tal...,11/21/2023 0:01,1700499693,NaN,https://external.fhan5-2.fna.fbcdn.net/emg1/v/...,[],...,https://www.facebook.com/LiverpoolFC/posts/899...,"{'th√≠ch': 982, 'y√™u th√≠ch': 183, 'th∆∞∆°ng th∆∞∆°n...",1175,NaN,67920382572,NaN,NaN,[],False,11/21/2023 1:00
1,8.992110e+14,Back-to-back PFA Premier League Fans‚Äô Player o...,Back-to-back PFA Premier League Fans‚Äô Player o...,LIVERPOOLFC.COM\nMohamed Salah named October's...,Back-to-back PFA Premier League Fans‚Äô Player o...,11/20/2023 22:00,1700492458,NaN,https://external.fhan5-2.fna.fbcdn.net/emg1/v/...,[],...,https://www.facebook.com/LiverpoolFC/posts/899...,"{'th√≠ch': 3638, 'y√™u th√≠ch': 902, 'haha': 1, '...",4594,NaN,67920382572,NaN,NaN,[],False,11/21/2023 1:00
2,8.990810e+14,Ryan's first goal in Red üòç\n\nA look back at o...,Ryan's first goal in Red üòç\n\nA look back at o...,NaN,Ryan's first goal in Red üòç\n\nA look back at o...,11/20/2023 21:10,1700489427,NaN,https://scontent.fhan5-2.fna.fbcdn.net/v/t15.5...,[],...,https://www.facebook.com/LiverpoolFC/posts/899...,"{'th√≠ch': 4072, 'y√™u th√≠ch': 1022, 'haha': 3, ...",5157,NaN,67920382572,NaN,NaN,[],False,11/21/2023 1:00
3,8.991520e+14,"Well in, Robbo üëè #Euro2024 üîú\n\nV√¢ng, Robbo üëè ...","Well in, Robbo üëè #Euro2024 üîú\n\nV√¢ng, Robbo üëè ...",NaN,"Well in, Robbo üëè #Euro2024 üîú",11/20/2023 20:01,1700485284,NaN,https://scontent.fhan5-2.fna.fbcdn.net/v/t39.3...,[],...,https://www.facebook.com/LiverpoolFC/posts/899...,"{'th√≠ch': 12735, 'y√™u th√≠ch': 3112, 'haha': 19...",16019,NaN,67920382572,NaN,8.991510e+14,['899151118246387'],False,11/21/2023 1:00
4,8.991290e+14,Two years ago today... Diogo üò≤\n\nNg√†y n√†y hai...,Two years ago today... Diogo üò≤\n\nNg√†y n√†y hai...,NaN,Two years ago today... Diogo üò≤,11/20/2023 19:20,1700482820,NaN,https://scontent.fhan5-2.fna.fbcdn.net/v/t15.5...,[],...,https://www.facebook.com/LiverpoolFC/posts/899...,"{'th√≠ch': 11699, 'y√™u th√≠ch': 2506, 'haha': 45...",14403,NaN,67920382572,NaN,NaN,[],False,11/21/2023 1:01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,8.948430e+14,J√ºrgen Klopp confirmed Joe Gomez and Ibrahima ...,J√ºrgen Klopp confirmed Joe Gomez and Ibrahima ...,LIVERPOOLFC.COM\nJ√ºrgen Klopp on Joe Gomez and...,J√ºrgen Klopp confirmed Joe Gomez and Ibrahima ...,11/13/2023 16:39,1699868360,NaN,https://external.fhan5-2.fna.fbcdn.net/emg1/v/...,[],...,https://www.facebook.com/LiverpoolFC/posts/894...,"{'th√≠ch': 7779, 'y√™u th√≠ch': 934, 'haha': 3, '...",8853,NaN,67920382572,NaN,NaN,[],False,11/21/2023 1:34
96,8.948350e+14,Anfield remembers.\n\nAnfield nh·ªõ.,Anfield remembers.\n\nAnfield nh·ªõ.,NaN,Anfield remembers.,11/13/2023 16:24,1699867442,NaN,https://scontent.fhan5-6.fna.fbcdn.net/v/t15.5...,[],...,https://www.facebook.com/LiverpoolFC/posts/894...,"{'th√≠ch': 13364, 'y√™u th√≠ch': 2481, 'haha': 8,...",16050,NaN,67920382572,NaN,NaN,[],False,11/21/2023 1:34
97,8.948210e+14,NaN,NaN,NaN,NaN,11/13/2023 15:50,1699865445,https://scontent.fhan5-6.fna.fbcdn.net/v/t39.3...,https://scontent.fhan5-6.fna.fbcdn.net/v/t39.3...,['https://scontent.fhan5-6.fna.fbcdn.net/v/t39...,...,https://www.facebook.com/LiverpoolFC/posts/894...,"{'th√≠ch': 2124, 'y√™u th√≠ch': 1076, 'haha': 1, ...",3331,NaN,67920382572,NaN,NaN,[],False,11/21/2023 1:35
98,8.944540e+14,Good morning üòÅüî¥\n\nCh√†o bu·ªïi s√°ng üòÅüî¥,Good morning üòÅüî¥\n\nCh√†o bu·ªïi s√°ng üòÅüî¥,NaN,Good morning üòÅüî¥,11/13/2023 15:13,1699863180,https://m.facebook.com/photo/view_full_size/?f...,https://scontent.fhan5-11.fna.fbcdn.net/v/t39....,['https://m.facebook.com/photo/view_full_size/...,...,https://www.facebook.com/LiverpoolFC/posts/894...,"{'th√≠ch': 26432, 'y√™u th√≠ch': 7266, 'haha': 15...",34107,NaN,67920382572,NaN,8.944540e+14,['894453552049477'],False,11/21/2023 1:35
99,8.955110e+14,Big Virg against Brentford üîù\n\nBig Virg ch·ªëng...,Big Virg against Brentford üîù\n\nBig Virg ch·ªëng...,NaN,Big Virg against Brentford üîù,11/14/2023 18:58,1699963121,NaN,https://scontent.fhan5-8.fna.fbcdn.net/v/t15.5...,[],...,https://www.facebook.com/LiverpoolFC/posts/895...,"{'th√≠ch': 39460, 'y√™u th√≠ch': 6610, 'haha': 12...",46476,NaN,67920382572,NaN,NaN,[],False,11/21/2023 1:28

### Ch·ªçn c·ªôt

In [11]:
new_df = df[["post_id", "post_text", "time", "comments","comments_full", "shares", "reactions", "reaction_count"]]

In [12]:
new_df

,post_id,post_text,time,comments,comments_full,shares,reactions,reaction_count
0,8.992690e+14,üî¥üó£Ô∏è Emile Heskey is the latest to tell the tal...,11/21/2023 0:01,16,"[{'comment_id': '1186163892166613', 'comment_u...",101,"{'th√≠ch': 982, 'y√™u th√≠ch': 183, 'th∆∞∆°ng th∆∞∆°n...",1175
1,8.992110e+14,Back-to-back PFA Premier League Fans‚Äô Player o...,11/20/2023 22:00,83,"[{'comment_id': '277210241476921', 'comment_ur...",31,"{'th√≠ch': 3638, 'y√™u th√≠ch': 902, 'haha': 1, '...",4594
2,8.990810e+14,Ryan's first goal in Red üòç\n\nA look back at o...,11/20/2023 21:10,49,"[{'comment_id': '388506910181825', 'comment_ur...",53,"{'th√≠ch': 4072, 'y√™u th√≠ch': 1022, 'haha': 3, ...",5157
3,8.991520e+14,"Well in, Robbo üëè #Euro2024 üîú\n\nV√¢ng, Robbo üëè ...",11/20/2023 20:01,150,"[{'comment_id': '314996431472511', 'comment_ur...",61,"{'th√≠ch': 12735, 'y√™u th√≠ch': 3112, 'haha': 19...",16019
4,8.991290e+14,Two years ago today... Diogo üò≤\n\nNg√†y n√†y hai...,11/20/2023 19:20,211,"[{'comment_id': '1028198778438522', 'comment_u...",211,"{'th√≠ch': 11699, 'y√™u th√≠ch': 2506, 'haha': 45...",14403
...,...,...,...,...,...,...,...,...
95,8.948430e+14,J√ºrgen Klopp confirmed Joe Gomez and Ibrahima ...,11/13/2023 16:39,114,"[{'comment_id': '707770537958734', 'comment_ur...",34,"{'th√≠ch': 7779, 'y√™u th√≠ch': 934, 'haha': 3, '...",8853
96,8.948350e+14,Anfield remembers.\n\nAnfield nh·ªõ.,11/13/2023 16:24,149,"[{'comment_id': '7303758222967701', 'comment_u...",309,"{'th√≠ch': 13364, 'y√™u th√≠ch': 2481, 'haha': 8,...",16050
97,8.948210e+14,NaN,11/13/2023 15:50,94,"[{'comment_id': '1042475023660878', 'comment_u...",23,"{'th√≠ch': 2124, 'y√™u th√≠ch': 1076, 'haha': 1, ...",3331
98,8.944540e+14,Good morning üòÅüî¥\n\nCh√†o bu·ªïi s√°ng üòÅüî¥,11/13/2023 15:13,417,"[{'comment_id': '1483340398900267', 'comment_u...",124,"{'th√≠ch': 26432, 'y√™u th√≠ch': 7266, 'haha': 15...",34107
99,8.955110e+14,Big Virg against Brentford üîù\n\nBig Virg ch·ªëng...,11/14/2023 18:58,631,"[{'comment_id': '304499032539488', 'comment_ur...",727,"{'th√≠ch': 39460, 'y√™u th√≠ch': 6610, 'haha': 12...",46476

In [13]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   post_id         100 non-null    float64
 1   post_text       98 non-null     object
 2   time            100 non-null    object
 3   comments        100 non-null    int64
 4   comments_full   100 non-null    object
 5   shares          100 non-null    int64
 6   reactions       100 non-null    object
 7   reaction_count  100 non-null    int64
dtypes: float64(1), int64(3), object(4)
memory usage: 6.4+ KB

### B·ªè h√†ng c√≥ gi√° tr·ªã r·ªóng

In [14]:
new_df_01 = new_df.dropna()

In [15]:
new_df_01.info()

<class 'pandas.core.frame.DataFrame'>
Index: 98 entries, 0 to 99
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   post_id         98 non-null     float64
 1   post_text       98 non-null     object
 2   time            98 non-null     object
 3   comments        98 non-null     int64
 4   comments_full   98 non-null     object
 5   shares          98 non-null     int64
 6   reactions       98 non-null     object
 7   reaction_count  98 non-null     int64
dtypes: float64(1), int64(3), object(4)
memory usage: 6.9+ KB

### L∆∞u l·∫°i v√†o t·ªáp Lp_select_column.csv

In [16]:
new_df_01.to_csv('C:/Users/Admin/aim/project_analysis_data_facebook/data/Lp_select_column.csv', index = False)