## T√°ch Reactions

### ƒê·ªçc file Lp_select_column.csv

In [5]:
import pandas as pd
import ast

In [2]:
df = pd.read_csv('C:/Users/Admin/aim/project_analysis_data_facebook/data/Lp_select_column.csv')

In [3]:
df

,post_id,post_text,time,comments,comments_full,shares,reactions,reaction_count
0,8.992690e+14,üî¥üó£Ô∏è Emile Heskey is the latest to tell the tal...,11/21/2023 0:01,16,"[{'comment_id': '1186163892166613', 'comment_u...",101,"{'th√≠ch': 982, 'y√™u th√≠ch': 183, 'th∆∞∆°ng th∆∞∆°n...",1175
1,8.992110e+14,Back-to-back PFA Premier League Fans‚Äô Player o...,11/20/2023 22:00,83,"[{'comment_id': '277210241476921', 'comment_ur...",31,"{'th√≠ch': 3638, 'y√™u th√≠ch': 902, 'haha': 1, '...",4594
2,8.990810e+14,Ryan's first goal in Red üòç\n\nA look back at o...,11/20/2023 21:10,49,"[{'comment_id': '388506910181825', 'comment_ur...",53,"{'th√≠ch': 4072, 'y√™u th√≠ch': 1022, 'haha': 3, ...",5157
3,8.991520e+14,"Well in, Robbo üëè #Euro2024 üîú\n\nV√¢ng, Robbo üëè ...",11/20/2023 20:01,150,"[{'comment_id': '314996431472511', 'comment_ur...",61,"{'th√≠ch': 12735, 'y√™u th√≠ch': 3112, 'haha': 19...",16019
4,8.991290e+14,Two years ago today... Diogo üò≤\n\nNg√†y n√†y hai...,11/20/2023 19:20,211,"[{'comment_id': '1028198778438522', 'comment_u...",211,"{'th√≠ch': 11699, 'y√™u th√≠ch': 2506, 'haha': 45...",14403
...,...,...,...,...,...,...,...,...
93,8.948540e+14,"""I really thank him because in this period he ...",11/13/2023 17:03,97,"[{'comment_id': '1120275918934925', 'comment_u...",43,"{'th√≠ch': 11518, 'y√™u th√≠ch': 1523, 'haha': 9,...",13139
94,8.948430e+14,J√ºrgen Klopp confirmed Joe Gomez and Ibrahima ...,11/13/2023 16:39,114,"[{'comment_id': '707770537958734', 'comment_ur...",34,"{'th√≠ch': 7779, 'y√™u th√≠ch': 934, 'haha': 3, '...",8853
95,8.948350e+14,Anfield remembers.\n\nAnfield nh·ªõ.,11/13/2023 16:24,149,"[{'comment_id': '7303758222967701', 'comment_u...",309,"{'th√≠ch': 13364, 'y√™u th√≠ch': 2481, 'haha': 8,...",16050
96,8.944540e+14,Good morning üòÅüî¥\n\nCh√†o bu·ªïi s√°ng üòÅüî¥,11/13/2023 15:13,417,"[{'comment_id': '1483340398900267', 'comment_u...",124,"{'th√≠ch': 26432, 'y√™u th√≠ch': 7266, 'haha': 15...",34107
97,8.955110e+14,Big Virg against Brentford üîù\n\nBig Virg ch·ªëng...,11/14/2023 18:58,631,"[{'comment_id': '304499032539488', 'comment_ur...",727,"{'th√≠ch': 39460, 'y√™u th√≠ch': 6610, 'haha': 12...",46476

### T·∫°o 1 list ch·ª©a c√°c dictionary c·ªßa c√°c lo·∫°i reaction c·ªßa t·ª´ng post v√† l∆∞u v√†o 1 list

In [6]:
react_list = []

for react_str in df.reactions:
    react_dict = ast.literal_eval(react_str)
    react_list.append(react_dict)

### T·∫°o dataframe t·ª´ react_list

In [7]:
df_reactions = pd.DataFrame(react_list)
df_reactions

    th√≠ch  y√™u th√≠ch  th∆∞∆°ng th∆∞∆°ng  haha   wow  bu·ªìn  ph·∫´n n·ªô
0     982        183             10   NaN   NaN   NaN      NaN
1    3638        902             49   1.0   4.0   NaN      NaN
2    4072       1022             55   3.0   4.0   1.0      NaN
3   12735       3112            146  19.0   6.0   1.0      NaN
4   11699       2506            125  45.0  26.0   1.0      1.0
..    ...        ...            ...   ...   ...   ...      ...
93  11518       1523             77   9.0   7.0   2.0      3.0
94   7779        934             85   3.0   9.0  39.0      4.0
95  13364       2481            174   8.0  13.0   7.0      3.0
96  26432       7266            385  15.0   6.0   2.0      1.0
97  39460       6610            353  12.0  38.0   1.0      2.0

[98 rows x 7 columns]

### Thay th·∫ø c√°c gi√° tr·ªã NaN b·∫±ng 0

In [8]:
df_reactions = df_reactions.fillna(0)

### B·ªè thu·ªôc t√≠nh reactions c≈©

In [9]:
no_react_df = df.drop(['reactions'], axis = 1)

### Thay thu·ªôc t√≠nh reactions b·∫±ng dataframe df_reactions

In [10]:
new_df = pd.concat([no_react_df, df_reactions], axis = 1)

In [11]:
new_df

,post_id,post_text,time,comments,comments_full,shares,reaction_count,th√≠ch,y√™u th√≠ch,th∆∞∆°ng th∆∞∆°ng,haha,wow,bu·ªìn,ph·∫´n n·ªô
0,8.992690e+14,üî¥üó£Ô∏è Emile Heskey is the latest to tell the tal...,11/21/2023 0:01,16,"[{'comment_id': '1186163892166613', 'comment_u...",101,1175,982,183,10,0.0,0.0,0.0,0.0
1,8.992110e+14,Back-to-back PFA Premier League Fans‚Äô Player o...,11/20/2023 22:00,83,"[{'comment_id': '277210241476921', 'comment_ur...",31,4594,3638,902,49,1.0,4.0,0.0,0.0
2,8.990810e+14,Ryan's first goal in Red üòç\n\nA look back at o...,11/20/2023 21:10,49,"[{'comment_id': '388506910181825', 'comment_ur...",53,5157,4072,1022,55,3.0,4.0,1.0,0.0
3,8.991520e+14,"Well in, Robbo üëè #Euro2024 üîú\n\nV√¢ng, Robbo üëè ...",11/20/2023 20:01,150,"[{'comment_id': '314996431472511', 'comment_ur...",61,16019,12735,3112,146,19.0,6.0,1.0,0.0
4,8.991290e+14,Two years ago today... Diogo üò≤\n\nNg√†y n√†y hai...,11/20/2023 19:20,211,"[{'comment_id': '1028198778438522', 'comment_u...",211,14403,11699,2506,125,45.0,26.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,8.948540e+14,"""I really thank him because in this period he ...",11/13/2023 17:03,97,"[{'comment_id': '1120275918934925', 'comment_u...",43,13139,11518,1523,77,9.0,7.0,2.0,3.0
94,8.948430e+14,J√ºrgen Klopp confirmed Joe Gomez and Ibrahima ...,11/13/2023 16:39,114,"[{'comment_id': '707770537958734', 'comment_ur...",34,8853,7779,934,85,3.0,9.0,39.0,4.0
95,8.948350e+14,Anfield remembers.\n\nAnfield nh·ªõ.,11/13/2023 16:24,149,"[{'comment_id': '7303758222967701', 'comment_u...",309,16050,13364,2481,174,8.0,13.0,7.0,3.0
96,8.944540e+14,Good morning üòÅüî¥\n\nCh√†o bu·ªïi s√°ng üòÅüî¥,11/13/2023 15:13,417,"[{'comment_id': '1483340398900267', 'comment_u...",124,34107,26432,7266,385,15.0,6.0,2.0,1.0
97,8.955110e+14,Big Virg against Brentford üîù\n\nBig Virg ch·ªëng...,11/14/2023 18:58,631,"[{'comment_id': '304499032539488', 'comment_ur...",727,46476,39460,6610,353,12.0,38.0,1.0,2.0

### L∆∞u l·∫°i v√†o file Lp_divide_reactions.csv

In [12]:
new_df.to_csv('C:/Users/Admin/aim/project_analysis_data_facebook/data/Lp_select_column.csv', index=False)